name: GitHub CI

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 0

defaults:
  run:
    shell: 'bash -Eeuo pipefail {0}'

jobs:
  main:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        version:
          - '0.14'
        suffix:
          - ""
          - "-slim"
          - "-full"

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=false
            suffix=${{ matrix.suffix }}
          tags: type=raw,value=${{ matrix.version }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          pull: true
          no-cache: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ matrix.version }}/Dockerfile${{ matrix.suffix }}
          context: ${{ matrix.version }}
      - run: docker run -d -e DEBUG=1 --name nanomq ghcr.io/${{ github.repository }}:${{ matrix.version }}${{ matrix.suffix }} --log_level debug
      - name: Check docker container
        run: |
          set -e -x -u
          sudo apt update && sudo apt install -y mosquitto-clients
          ip_address=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nanomq)
          sleep 5
          mosquitto_pub -h $ip_address -t 'topic/A' -m 'test'
